In [ ]:
!git clone https://github.com/FlorentF9/SOMperf.git

Cloning into 'SOMperf'...
remote: Enumerating objects: 101, done.
remote: Counting objects: 100% (101/101), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 101 (delta 44), reused 86 (delta 31), pack-reused 0
Receiving objects: 100% (101/101), 595.65 KiB | 9.02 MiB/s, done.
Resolving deltas: 100% (44/44), done.


In [ ]:
import os
os.chdir('SOMperf')

In [ ]:
!python3 setup.py install

running install
running bdist_egg
running egg_info
creating SOMperf.egg-info
writing SOMperf.egg-info/PKG-INFO
writing dependency_links to SOMperf.egg-info/dependency_links.txt
writing requirements to SOMperf.egg-info/requires.txt
writing top-level names to SOMperf.egg-info/top_level.txt
writing manifest file 'SOMperf.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'SOMperf.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/somperf
copying somperf/__init__.py -> build/lib/somperf
copying somperf/__version__.py -> build/lib/somperf
creating build/lib/somperf/utils
copying somperf/utils/neighborhood.py -> build/lib/somperf/utils
copying somperf/utils/__init__.py -> build/lib/somperf/utils
copying somperf/utils/topology.py -> build/lib/somperf/utils
creating build/lib/somperf/metrics
copying somperf/metrics/__init__.py -> build/lib/somperf/metrics


In [ ]:
!pip install minisom

  Created wheel for minisom: filename=MiniSom-2.2.9-cp37-none-any.whl size=8595 sha256=d3bb002393ebfd148d886086344bb05d8a4d5f5b83e25b9f2bec2ebf57835941
  Stored in directory: /root/.cache/pip/wheels/de/a0/08/5234d6b02b29c561f62b6c985e2eb7d480fb0b92359a8c74e4
Successfully built minisom


In [ ]:
import numpy as np
from minisom import MiniSom

from somperf.metrics import *
from somperf.utils.topology import rectangular_topology_dist

# 8 colors
X = np.array([[1.0, 0.0, 0.0],
              [0.0, 1.0, 0.0],
              [0.0, 0.0, 1.0],
              [1.0, 1.0, 1.0],
              [0.5, 0.5, 0.5],
              [1.0, 1.0, 0.0],
              [0.0, 1.0, 1.0],
              [1.0, 0.0, 1.0]])

# define and train 10-by-10 map
map_size = (10, 10)
som = MiniSom(map_size[0], map_size[1], X.shape[-1], sigma=1.0, learning_rate=1.0, random_seed=42)
som.random_weights_init(X)
som.train_random(X, 10000)

# get weights as a (100, 3) array
weights = som.get_weights().reshape(map_size[0]*map_size[1], -1)

# compute a few metrics
print('Topographic product = ', topographic_product(rectangular_topology_dist(map_size), weights))
print('Neighborhood preservation = ', neighborhood_preservation(1, weights, X))
print('Trustworthiness = ', trustworthiness(1, weights, X))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.metrics.cluster.supervised module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics.cluster. Anything that cannot be imported from sklearn.metrics.cluster is now part of the private API.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:22: FutureWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Topographic product =  0.4333384232803905
Neighborhood preservation =  0.9375
Trustworthiness =  1.0


In [ ]:
import numpy as np

map_size = (4,4)

w = [[ 1.29762733 , 0.2625703  ,0.08273311],
 [ 0.87336098  ,0.8314740 ,-0.04326703],
 [ 0.17989823 , 0.4356558 , 0.46427652],
[-0.52103301, -0.1619089,  1.03110278],
[ 0.87336107 , 0.8314743 ,-0.04326738],
[  0.74987617 , 1.1056883, -0.73339329],
[  0.07372646 , 0.3221188, -0.41696859],
[ -0.38969272, -0.4155602 , 0.29905970],
[  0.18992068 , 0.4422200 , 0.45766536],
[  0.07372641, 0.3221188, -0.41696851],
[  0.12320130 ,-0.2557705, -1.00428194],
[ -0.52723619, -0.5730274 ,-0.66660758],
[ -0.52103302 ,-0.1619089,  1.03110286],
[ -0.38256470, -0.4479080 , 0.18870270],
[ -0.54557199 ,-0.5884401 ,-0.65777586],
[ -1.21942047, -0.9271189, -0.58570895]]

t = np.array(w)

t

array([[ 1.29762733,  0.2625703 ,  0.08273311],
       [ 0.87336098,  0.831474  , -0.04326703],
       [ 0.17989823,  0.4356558 ,  0.46427652],
       [-0.52103301, -0.1619089 ,  1.03110278],
       [ 0.87336107,  0.8314743 , -0.04326738],
       [ 0.74987617,  1.1056883 , -0.73339329],
       [ 0.07372646,  0.3221188 , -0.41696859],
       [-0.38969272, -0.4155602 ,  0.2990597 ],
       [ 0.18992068,  0.44222   ,  0.45766536],
       [ 0.07372641,  0.3221188 , -0.41696851],
       [ 0.1232013 , -0.2557705 , -1.00428194],
       [-0.52723619, -0.5730274 , -0.66660758],
       [-0.52103302, -0.1619089 ,  1.03110286],
       [-0.3825647 , -0.447908  ,  0.1887027 ],
       [-0.54557199, -0.5884401 , -0.65777586],
       [-1.21942047, -0.9271189 , -0.58570895]])

In [ ]:
import pandas as pd
df = pd.read_csv("/../content/binary.csv")
df = df.drop(columns=["admit"])
n = df.values

In [ ]:
print('Topographic product = ', topographic_product(rectangular_topology_dist(map_size), t))
print('Neighborhood preservation = ', neighborhood_preservation(1, t, n))
print('Trustworthiness = ', trustworthiness(1, t, n))

Topographic product =  0.5530599677605338
Neighborhood preservation =  1.0
Trustworthiness =  0.48515598040326957


In [ ]:
prototypes = make_grid(*map_size)
dist_fun = rectangular_topology_dist(map_size)
kruskal_shepard_error(dist_fun=dist_fun, som=t, x=n)

/content/SOMperf/somperf/metrics/internal.py:179: RuntimeWarning: invalid value encountered in true_divide
  d_som /= d_som.max()


nan

In [ ]:
def test_equal(somperf_value, expected_value):
    print("ok") if np.round(somperf_value, 9) == np.round(expected_value, 9) else print("nok")

def test_all_equal(somperf_values, expected_values):
    display(ok) if (np.round(somperf_values, 9) == np.round(expected_values, 9)).all() else display(nok)

def test_decreasing(somperf_values):
    display(ok) if (np.diff(somperf_values) <= 0.0).all() else display(nok)

def test_increasing(somperf_values):
    display(ok) if (np.diff(somperf_values) >= 0.0).all() else display(nok)

In [ ]:
expected_value = 0.333333333
somperf_value = neighborhood_preservation(k=1, som=t, x=n)

test_equal(somperf_value, expected_value)

nok


In [ ]:
import numpy as np
import pandas as pd
map_size = (30,30)

df = pd.read_csv("/../content/Sid_w.csv")
t = np.array(df)

t

array([[ 1.48775709e+00, -5.78343291e-01,  8.50278027e-01,
        -2.11032163e+00],
       [-1.89190100e-03, -8.26672466e-01,  1.13952725e+00,
         1.03959965e+00],
       [ 1.38102079e+00, -2.44312030e+00, -1.55392368e+00,
        -8.88081865e-01],
       ...,
       [ 1.83177846e+00,  1.61769624e+00,  1.54698510e+00,
         2.07241261e+00],
       [ 1.84248448e+00,  9.38005831e-01,  1.19548944e+00,
         1.90723986e+00],
       [ 1.21394421e+00,  1.98485282e+00,  1.18702943e+00,
         2.26931470e+00]])

In [ ]:
df1 = pd.read_csv("/../content/Sid_data.csv")
df1 = df1[["Confirmed","Recovered","Deaths","Active"]]
df1

Confirmed  Recovered  Deaths   Active
0    29358514   27903214  367106  1076736
1        7233       6984     125      124
2     1796122    1688198   11824    96100
3       30850      27438     138     3274
4      453867     403170    3873    45477
5      716296     700481    9466     6348
6       60998      59648     786      564
7      985691     956459   13300    15932
8       10455      10312       4      108
9     1430671    1401977   24772     3922
10     161576     153476    2899     5201
11     819376     797734    9985    11657
12     765096     750443    8904     5749
13     197943     188691    3351     5879
14     305772     284027    4160    17585
15     343065     333763    5082     4220
16    2747539    2511105   32644   203769
17    2702823    2557597   10804   134001
18      19475      18425     197      853
19       9122       8382      43      665
20     787572     773615    8510     5447
21    5887853    5616857  106367   161704
22      58768      48902     944     8922
23      41100      35393     714     4993
24      14743      11358      61     3324
25      23466      18587     445     3777
26     842461     781488    3263    57710
27     111684     103860    1668     6156
28     585986     555245   15435    15306
29     949008     931186    8799     9023
30      18090      13655     281     3908
31          0          0       0        0
32    2324597    2120889   28906   174802
33     600318     574103    3456    22759
34      58090      51593     593     5881
35    1701668    1668874   21667    11127
36     336153     318235    6909     5277
37    1452987    1421064   16731    15192

In [ ]:
n = df1.values
n

array([[29358514, 27903214,   367106,  1076736],
       [    7233,     6984,      125,      124],
       [ 1796122,  1688198,    11824,    96100],
       [   30850,    27438,      138,     3274],
       [  453867,   403170,     3873,    45477],
       [  716296,   700481,     9466,     6348],
       [   60998,    59648,      786,      564],
       [  985691,   956459,    13300,    15932],
       [   10455,    10312,        4,      108],
       [ 1430671,  1401977,    24772,     3922],
       [  161576,   153476,     2899,     5201],
       [  819376,   797734,     9985,    11657],
       [  765096,   750443,     8904,     5749],
       [  197943,   188691,     3351,     5879],
       [  305772,   284027,     4160,    17585],
       [  343065,   333763,     5082,     4220],
       [ 2747539,  2511105,    32644,   203769],
       [ 2702823,  2557597,    10804,   134001],
       [   19475,    18425,      197,      853],
       [    9122,     8382,       43,      665],
       [  787572,   

In [ ]:
print('Topographic product = ', topographic_product(rectangular_topology_dist(map_size), t))
print('Neighborhood preservation = ', neighborhood_preservation(1, t, n))
print('Trustworthiness = ', trustworthiness(1, t, n))

Topographic product =  -0.06179395889903062
Neighborhood preservation =  1.0
Trustworthiness =  0.5026600064977259
